const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 30,
      brand: 'Adidas',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 50,
      brand: 'Lacoste',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 35,
      brand: 'Adidas',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 90,
      brand: 'Oliver',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Pants',
      category: 'Pants',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Zara',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Pants',
    },
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};
