const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 30,
      brand: 'Adidas',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 50,
      brand: 'Lacoste',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free Pants',
      slug: 'free-pants',
      category: 'Shirts',
      image: '/images/pants1.jpg',
      price: 35,
      brand: 'Adidas',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'glof-pants',
      category: 'Shirts',
      image: '/images/pants2.jpg',
      price: 90,
      brand: 'Oliver',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 70,
      brand: 'Zara',
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Pants',
    },
  ],
};

export default data;
